### ISSUE TITLE
Help for "folder"

### ISSUE THREAD

**Issue by hartenthaler** [garraflavatra/webtrees-media-folder-import#1]
You mentioned 

> It's also possible to search for a folder by using the autocomplete feature.

How can I activate that?

I tried as folder "data/media" or "/data/media/", but those folders are not found. There is no error message, but it indicates "0 records have been created".

**Comment by garraflavatra** [comment]
Thank you for your question. The path you should enter is relative to your media directory (i.e. `data/media`. In the case you want to import all unused media files at the root of your media directory case, you just enter `/`.

Autocomplete is only useful when you have folders :) but it may autocomplete `/` too.

Please let me know if it works, or if you have any further questions.

**Comment by hartenthaler** [comment]
Thank you! It works! Maybe you can add a explanation sentence to the READme. 

And maybe an information that each image file in the folder will go to one GEDCOM media object (in principle, a media object could contain several media files).

**Comment by hartenthaler** [comment]
Thank you for this module! I just added it to the [list of custom modules in the German webtrees manual](https://wiki.genealogy.net/Webtrees_Handbuch/Anleitung_f%C3%BCr_Webmaster/Erweiterungsmodule).

**Comment by garraflavatra** [comment]
Glad to hear it works, and thank you for adding it to the list!
