### ISSUE TITLE
Module not showing

### ISSUE THREAD

**Issue by dax29** [garraflavatra/webtrees-media-folder-import#2]
Hi
I've downloaded this module and uploaded it to my webtrees site into the modules_v4>webtrees-media-folder-import-1.0.0 folder but its not showing up on my site in the Control Panel>all modules.
Any suggestions?
Cheers
Frank

**Comment by garraflavatra** [comment]
Hi Frank, thank you for trying my module. 

Webtrees ignores plugin folders with names that contain a period (in your case the `1.0.0` in `webtrees-media-folder-import-1.0.0`). This allows for disabling certain modules by renaming their directory names. Please try renaming it to `media-folder-import` or something similar without a period. I think that will resolve the issue.

I'll add a note in the readme as well.

Please let me know if it works, and feel free to contact me if you have any more questions!

Cheers, Romein

**Comment by dax29** [comment]
Hi Romein
Thanks for the tip and yes that worked, I changed the folder to
webtrees-media-folder-import.
Thanks again for your quick assistance

Cheers Frank

**Comment by garraflavatra** [comment]
Great! 👍
